# Generated by Django 6.0 on 2025-12-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_teacher_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='middlename',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='specialization',
            unique_together={('teacher', 'specialization')},
        ),
    ]
