# Generated by Django 6.0 on 2025-12-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreateEvent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendevent',
            name='status',
            field=models.CharField(choices=[('JOINED', 'ATTENDING'), ('NOT JOINED', 'NOT ATTENDING')], default='JOINED', max_length=20),
        ),
    ]
